---
  apiVersion: v1
  kind: Service
  metadata:
    name: jenkins
    labels:
      app: jenkins
      version: 2.7.4.096
      tier: frontend
      track: stable

  spec:
    type: LoadBalancer
    selector: 
      app: jenkins

    ports:
      - 
        name: http
        port: 80
        targetPort: 8080
        protocol: TCP

      - 
        name: slave
        port: 50000
        protocol: TCP
