---
  apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: jenkins
  spec:
    hard:
      pods: "30"
      requests.cpu: "1"
      requests.memory: 1Gi
      limits.cpu: "2"
      limits.memory: 7Gi