#
# http://kubernetes.io/docs/user-guide/services/
# http://kubernetes.io/docs/user-guide/configuring-containers/
#
---
  apiVersion: v1
  kind: Service
  metadata:
    name: jenkins-service
    labels:
      app: jenkins
      tier: frontend

  spec:
    type: LoadBalancer
    selector: 
      app: jenkins

    ports:
      - 
        name: http
        port: 80
        targetPort: 8080
        protocol: TCP

      - 
        name: slave
        port: 50000
        protocol: TCP
